(function(root,factory){const api=typeof module==='object'&&module.exports?factory(require('./simulation.js'),require('./world.js'),require('./territory.js'),require('./fog.js')):factory(root.Frontiers,root.World,root.Territory,root.Fog);if(typeof module==='object'&&module.exports)module.exports=api;else root.Campaign=api;})(globalThis,function(F,W,T,Fog){
 'use strict';
 const FACTIONS={union:{name:'Arden Union',description:'Industry +20%; balanced forces.'},vanguard:{name:'Iron Vanguard',description:'Armour health +20%; tank cost +10%.'},rangers:{name:'Frontier League',description:'Movement +15%; infantry recruits 25% faster.'}};
 const BUILDINGS={barracks:{name:'Barracks',cost:120,time:12,hp:260,units:['infantry']},garage:{name:'Vehicle depot',cost:200,time:20,hp:360,units:['mech','tank']},battery:{name:'Artillery emplacement',cost:240,time:24,hp:240,units:[],range:3200,radius:240,reload:12,ammo:18},trench:{name:'Infantry trench',cost:60,time:8,hp:320,units:[]},supply:{name:'Supply depot',cost:100,time:12,hp:260,units:[]},industry:{name:'Machine works',cost:220,time:25,hp:320,units:[]},refinery:{name:'Oil refinery',cost:180,time:22,hp:280,units:[]}};
 const TROOPS={infantry:{name:'Infantry',materiel:45,fuel:0,manpower:30,time:12,hp:100,speed:62,range:150,damage:8},mech:{name:'Mechanised',materiel:90,fuel:20,manpower:20,time:18,hp:140,speed:115,range:190,damage:10},tank:{name:'Armour',materiel:140,fuel:35,manpower:15,time:24,hp:190,speed:88,range:240,damage:16},artillery:{name:'Artillery',materiel:180,fuel:25,manpower:15,time:28,hp:95,speed:65,range:820,damage:38}};
 const region=(c,id)=>c.regions.find(r=>r.id===id),at=(c,x,y)=>{const r=W.regionAt(x,y);return r?region(c,r.id):null;},companies=c=>c.units.filter(u=>u.side==='blue'&&u.hp>0);
 function emit(c,message,source){c.events.push({time:c.time,message,visibleToPlayer:!source||!c.fog||source.side==='blue'||source.owner==='blue'||Fog.visible(c,source.x,source.y)});if(c.events.length>8)c.events.shift();}
 function mapFor(c){
  let mask=-1,indices=[],revision='';
  // Bridge health can change during a tick, so check its compact signature on every query.
  // Allocate a new navigation list only when a crossing actually opens or closes.
  function blocked(){let next=0;for(const b of c.bridges)if(b.hp<=0)next+=2**b.index;if(next!==mask){mask=next;indices=c.bridges.filter(b=>b.hp<=0).map(b=>b.index);revision=indices.join(',');}return indices;}
  return {...W,revision:()=>{blocked();return revision;},visible:(a,b)=>W.visible(a,b,blocked()),walkable:(x,y)=>W.walkable(x,y,blocked()),route:(a,b)=>W.route(a,b,blocked())};
 }
 function makeBuilding(c,type,x,y,side,complete=false){const d=BUILDINGS[type],b={id:'building-'+c.nextBuilding++,name:d.name,type,x,y,regionId:at(c,x,y)?.id,owner:side,hp:d.hp,maxHp:d.hp,level:1,remaining:complete?0:d.time,queue:[],rally:{x:x+120,y:y+50},repair:false};c.buildings.push(b);return b;}
 function spawn(c,type,side,p){if(!c.map.walkable(p.x,p.y)){let found=null;for(let radius=25;radius<=400&&!found;radius+=25)for(let a=0;a<Math.PI*2;a+=Math.PI/8){const q={x:p.x+Math.cos(a)*radius,y:p.y+Math.sin(a)*radius};if(c.map.walkable(q.x,q.y)){found=q;break;}}if(found)p=found;}const d=TROOPS[type],number=side==='blue'?c.nextBlue++:c.nextRed++,id=side==='blue'&&number<=9?String.fromCharCode(96+number):side+'-'+number,label=String(number),u=F.formation(id,d.name+' '+label,side,type,p.x,p.y);Object.assign(u,{label,hp:d.hp,maxHp:d.hp,range:d.range,speed:d.speed,damage:d.damage,supply:1,fuel:1,home:{...p},strategyTimer:0,raider:side==='red',mobilizeAt:c.time+45});if(side==='blue'&&c.faction==='vanguard'&&type==='tank')u.hp=u.maxHp=d.hp*1.2;if(side==='blue'&&c.faction==='rangers')u.speed*=1.15;c.units.push(u);return u;}
 function create(options={}){
  const c=F.create();Object.assign(c,{version:1,map:W,regional:true,units:[],selected:null,factory:null,materiel:600,fuel:220,manpower:250,enemyFunds:500,enemyFuel:200,enemyManpower:250,buildings:[],nextBuilding:1,nextUnit:1,nextBlue:1,nextRed:1,selectedRegion:'westhaven',faction:FACTIONS[options.faction]?options.faction:'union',mode:options.mode==='long'?'long':'short',autoRetreat:true,shells:[],explosions:[],craters:[],logisticsClock:0,aiClock:0,score:{blue:0,red:0},elapsedLimit:options.mode==='long'?2700:1200});
  c.regions=W.regions.map(r=>({...r,claimed:r.owner==='blue',ground:{blue:r.owner==='blue'?1:0,red:r.owner==='red'?1:0},factory:{x:r.x,y:r.y,hp:350,maxHp:350,owner:r.owner,name:r.facility,regionName:r.name,production:r.production,capture:r.owner==='blue'?100:0,repair:false}}));c.facilities=c.regions.map(r=>r.factory);
  c.bridges=W.bridges.map((y,index)=>({id:'bridge-'+index,index,name:['North crossing','Central crossing','South crossing'][index],x:W.riverX(y),y,hp:400,maxHp:400,owner:'neutral',repair:false}));c.map=mapFor(c);const home=region(c,'westhaven');c.depot={x:home.x,y:home.y};
  for(const r of c.regions){if(r.owner==='blue'){for(let i=0;i<4;i++)spawn(c,i===0&&r.id!=='grey-ridge'?'tank':'infantry','blue',{x:r.x-180+(i%2)*100,y:r.y-180+Math.floor(i/2)*90});}else{const count=r.owner==='neutral'?1:4;for(let i=0;i<count;i++){const u=spawn(c,r.owner==='neutral'?'infantry':['tank','infantry','infantry','infantry'][i],'red',{x:r.x+100+i*65,y:r.y-100+i*70});if(r.owner==='neutral'){u.hp=u.maxHp=55;u.damage=5;u.raider=false;u.militia=true;}}}}
  for(const [type,dx,dy] of [['barracks',-90,90],['garage',80,90],['battery',180,90]])makeBuilding(c,type,home.x+dx,home.y+dy,'blue',true);
  for(const r of c.regions.filter(r=>r.owner==='red'))makeBuilding(c,r.id==='eastwatch'?'battery':r.neighbours.length%2?'barracks':'garage',r.x-80,r.y+80,'red',true);
  c.territory=T.create(c,W);logistics(c,0);Fog.update(c,W,true);emit(c,'Operation begins. Secure towns, build industry and keep your supply roads open.');return c;
 }
 function territoryOwner(c,p){const size=c.territory.size,x=Math.floor(p.x/size)*size,y=Math.floor(p.y/size)*size;return c.territory.cells.find(cell=>cell.x===x&&cell.y===y)?.owner;}
 function placement(c,type,p,side='blue'){const d=BUILDINGS[type];if(!d)return 'Choose a building.';if(!c.map.walkable(p.x,p.y))return 'Place on dry, reachable land.';if(type==='trench'&&[-110,-55,0,55,110].some(dx=>[-38,0,38].some(dy=>{const a=p.angle||0,q={x:p.x+dx*Math.cos(a)-dy*Math.sin(a),y:p.y+dx*Math.sin(a)+dy*Math.cos(a)};return !c.map.walkable(q.x,q.y)||territoryOwner(c,q)!==side;})))return 'The entire trench must fit on controlled dry land.';const r=at(c,p.x,p.y);if(!r||r.owner!==side||territoryOwner(c,p)!==side)return 'Build inside territory your forces control.';if(type!=='trench'&&W.roadDistance(p)>220)return 'Connect to a road: place within 220 m of one.';if(c.buildings.some(b=>F.distance(b,p)<100)||c.facilities.some(f=>F.distance(f,p)<90))return 'Leave space around existing buildings.';if(c.buildings.filter(b=>b.owner===side).length>=40)return 'Building limit reached (40 per side).';if((side==='blue'?c.materiel:c.enemyFunds)<d.cost)return 'Not enough materiel.';return null;}
 function construct(c,type,p){const error=placement(c,type,p);if(error)return error;c.materiel-=BUILDINGS[type].cost;const b=makeBuilding(c,type,p.x,p.y,'blue');if(type==='trench')b.angle=Number.isFinite(p.angle)?p.angle:0;emit(c,b.name+' construction started.');return b;}
 function costs(c,type,side){const d=TROOPS[type];return {...d,materiel:Math.ceil(d.materiel*(side==='blue'&&c.faction==='vanguard'&&type==='tank'?1.1:1)),time:d.time*(side==='blue'&&c.faction==='rangers'&&type==='infantry'?.75:1)};}
 function recruit(c,buildingId,type){const b=c.buildings.find(b=>b.id===buildingId),d=TROOPS[type];if(!b||b.owner!=='blue'||!d||!BUILDINGS[b.type].units.includes(type))return 'Choose a suitable production building.';if(b.hp<=0||b.remaining>0)return 'Finish or repair this building first.';if(b.queue.length>=5)return 'Queue full (5 companies).';if(c.units.filter(u=>u.side==='blue'&&u.hp>0).length+c.buildings.filter(b=>b.owner==='blue').reduce((n,b)=>n+b.queue.length,0)>=60)return 'Army limit reached (60 companies).';const cost=costs(c,type,'blue');if(c.materiel<cost.materiel||c.fuel<cost.fuel||c.manpower<cost.manpower)return 'Need '+cost.materiel+' materiel, '+cost.fuel+' fuel and '+cost.manpower+' manpower.';c.materiel-=cost.materiel;c.fuel-=cost.fuel;c.manpower-=cost.manpower;b.queue.push({type,remaining:cost.time,total:cost.time,cost});return type+' queued.';}
 function cancelQueue(c,id){const b=c.buildings.find(b=>b.id===id&&b.owner==='blue'),q=b?.queue.pop();if(!q)return 'Queue is empty.';c.materiel+=q.cost.materiel;c.fuel+=q.cost.fuel;c.manpower+=q.cost.manpower;return 'Last order cancelled; resources refunded.';}
 function upgrade(c,id){const b=c.buildings.find(b=>b.id===id&&b.owner==='blue');if(!b||b.hp<=0||b.remaining>0)return 'Choose an operational building.';if(b.level>=3)return 'Maximum level reached.';const cost=150*b.level;if(c.materiel<cost)return 'Upgrade costs '+cost+' materiel.';c.materiel-=cost;b.level++;b.maxHp+=100;b.hp+=100;return 'Upgraded to level '+b.level+'.';}
 function infrastructure(c,id){return [...c.buildings,...c.bridges].find(b=>b.id===id);}
 function repair(c,id){const b=infrastructure(c,id);if(!b)return 'Choose a building or bridge.';const r=at(c,b.x,b.y);if(b.owner!=='blue'&&!(b.index!==undefined&&r?.owner==='blue'))return 'Control this location before repairing it.';if(b.hp>=b.maxHp)return 'Already operational.';b.repair=!b.repair;return b.repair?'Repair crews assigned; 8 materiel per second.':'Repairs paused.';}
 function supplyRegions(c,side){const capital=region(c,side==='blue'?'westhaven':'eastwatch'),owned=new Set();if(capital.owner!==side||capital.factory.hp<=0)return owned;owned.add(capital.id);let changed=true;while(changed){changed=false;for(const link of W.roadLinks){if(link.bridges.some(i=>c.bridges[i].hp<=0))continue;const a=region(c,link.from),b=region(c,link.to);if(a.owner!==side||b.owner!==side||a.factory.hp<=0||b.factory.hp<=0)continue;if(owned.has(a.id)&&!owned.has(b.id)){owned.add(b.id);changed=true;}if(owned.has(b.id)&&!owned.has(a.id)){owned.add(a.id);changed=true;}}}return owned;}
 function logistics(c,dt){const networks={blue:supplyRegions(c,'blue'),red:supplyRegions(c,'red')};for(const r of c.regions)r.supplied=networks[r.owner]?.has(r.id)||false;
  for(const u of c.units){if(u.hp<=0)continue;const r=at(c,u.x,u.y),local=r?.owner===u.side&&r.supplied,forward=c.buildings.some(b=>b.type==='supply'&&b.owner===u.side&&b.hp>0&&!b.remaining&&at(c,b.x,b.y)?.supplied&&F.distance(b,u)<900);u.supplied=local||forward;u.supply=F.clamp((u.supply??1)+(u.supplied?.09:-.012)*dt,0,1);u.fuel??=1;if(u.type!=='infantry'){if(u.moving)u.fuel=Math.max(0,u.fuel-.003*dt);const pool=u.side==='blue'?'fuel':'enemyFuel';if(u.supplied&&u.fuel<1&&c[pool]>.1){const amount=Math.min(.1*dt,1-u.fuel,c[pool]/5);u.fuel+=amount;c[pool]-=amount*5;}}if(u.supply===0)u.hp=Math.max(0,u.hp-.2*dt);if(u.side==='blue'&&c.autoRetreat&&u.hp<u.maxHp*.25&&!['repair','move'].includes(u.order)){F.command(c,u.id,'repair');emit(c,u.name+' is withdrawing at critical strength.');}if(u.side==='red'&&u.order==='withdraw'&&u.supplied)u.hp=Math.min(u.maxHp,u.hp+2*dt);}
  for(const r of c.regions){if(!['blue','red'].includes(r.owner))continue;const health=r.factory.hp/r.factory.maxHp,connected=r.supplied?1:.2;const blue=r.owner==='blue';if(blue){c.fuel+=.35*health*connected*dt;c.manpower+=.3*health*connected*dt;if(c.faction==='union')c.materiel+=r.production*.2*health*dt;}else{c.enemyFunds+=r.production*health*connected*dt;c.enemyFuel+=.35*health*connected*dt;c.enemyManpower+=.3*health*connected*dt;}}
 }
 function production(c,dt){for(const b of c.buildings){const r=at(c,b.x,b.y),connected=r?.owner===b.owner&&r.supplied;if(b.repair&&b.hp<b.maxHp&&c.materiel>0){const heal=Math.min(10*dt,b.maxHp-b.hp,c.materiel/ .8);b.hp+=heal;c.materiel-=heal*.8;if(b.hp>=b.maxHp)b.repair=false;}if(b.hp<=0)continue;if(b.remaining>0){b.remaining=Math.max(0,b.remaining-dt);continue;}if(!connected)continue;const rate=1+(b.level-1)*.3,health=b.hp/b.maxHp;if(b.type==='industry'){if(b.owner==='blue')c.materiel+=2*rate*health*dt;else c.enemyFunds+=2*rate*health*dt;}if(b.type==='refinery'){if(b.owner==='blue')c.fuel+=1.2*rate*health*dt;else c.enemyFuel+=1.2*rate*health*dt;}if(b.type==='barracks'){if(b.owner==='blue')c.manpower+=.5*rate*dt;else c.enemyManpower+=.5*rate*dt;}const q=b.queue[0];if(!q)continue;q.remaining-=dt*rate*health;if(q.remaining<=0){const u=spawn(c,q.type,b.owner,{x:b.x,y:b.y-75});u.path=c.map.route(u,b.rally);u.order='advance';b.queue.shift();emit(c,u.name+' deployed.',u);}}
  for(const b of c.bridges)if(b.repair&&b.hp<b.maxHp&&c.materiel>0){const heal=Math.min(10*dt,b.maxHp-b.hp,c.materiel/.8);b.hp+=heal;c.materiel-=heal*.8;if(b.hp>=b.maxHp)b.repair=false;}
 }
 function strategy(c){const active=c.units.filter(u=>u.side==='red'&&u.hp>0&&!u.militia),friendly=c.units.filter(u=>u.side==='blue'&&u.hp>0),threatened=c.regions.filter(r=>r.owner==='red'&&friendly.some(v=>F.distance(v,r)<900)),targets=threatened.length?threatened:c.regions.filter(r=>r.owner!=='red');for(const u of active){if(c.time<u.mobilizeAt||u.hp<u.maxHp*.3)continue;const target=targets.reduce((best,r)=>!best||F.distance(u,r)<F.distance(u,best)?r:best,null);if(target){u.objective={x:target.x+(Number(u.label)%3-1)*80,y:target.y};u.path=c.map.route(u,u.objective);u.order='advance';}}
  if(c.enemyFunds>400&&c.buildings.filter(b=>b.owner==='red').length<16){const r=c.regions.find(r=>r.owner==='red'&&r.supplied&&!c.buildings.some(b=>b.owner==='red'&&at(c,b.x,b.y)?.id===r.id));if(r)for(const [dx,dy] of [[-200,0],[200,0],[0,-200],[0,200]]){const p={x:r.x+dx,y:r.y+dy};if(!placement(c,'barracks',p,'red')){c.enemyFunds-=BUILDINGS.barracks.cost;makeBuilding(c,'barracks',p.x,p.y,'red');break;}}}let reserved=active.length+c.buildings.filter(b=>b.owner==='red').reduce((n,b)=>n+b.queue.length,0);if(reserved>=55)return;for(const b of c.buildings.filter(b=>b.owner==='red'&&!b.remaining&&b.hp>0&&at(c,b.x,b.y)?.supplied)){if(reserved>=55)break;if(b.queue.length)continue;const choices=BUILDINGS[b.type].units,type=choices[Math.floor(c.time/20)%choices.length];if(!type)continue;if(type!=='infantry'){const infantry=active.filter(u=>u.type==='infantry').length,vehicles=active.length-infantry,queued=c.buildings.filter(x=>x.owner==='red').flatMap(x=>x.queue);if((vehicles+queued.filter(q=>q.type!=='infantry').length+1)*3>infantry+queued.filter(q=>q.type==='infantry').length)continue;}const d=costs(c,type,'red');if(c.enemyFunds>=d.materiel&&c.enemyFuel>=d.fuel&&c.enemyManpower>=d.manpower){c.enemyFunds-=d.materiel;c.enemyFuel-=d.fuel;c.enemyManpower-=d.manpower;b.queue.push({type,remaining:d.time,total:d.time,cost:d});reserved++;}}
 }
 function batteryOrder(c,id,p){const b=c.buildings.find(b=>b.id===id&&b.owner==='blue'&&b.type==='battery');if(!b)return 'Choose your artillery emplacement.';if(c.winner)return 'Campaign concluded.';if(b.hp<=0||b.remaining>0)return 'Finish or repair this emplacement first.';if(!Number.isFinite(p.x)||!Number.isFinite(p.y)||!c.map.land(p.x,p.y))return 'Target land or a crossing.';if(F.distance(b,p)>BUILDINGS.battery.range)return 'Target beyond battery range (3,200 m).';b.fireTarget={x:p.x,y:p.y};return 'Bombardment ordered · repeats every 12 seconds while supplied · 18 materiel per volley.';}
 function batteries(c,dt){const d=BUILDINGS.battery;for(const b of c.buildings){if(b.type!=='battery')continue;b.cooldown=Math.max(0,(b.cooldown||0)-dt);const r=at(c,b.x,b.y),connected=r?.owner===b.owner&&r.supplied,pool=b.owner==='blue'?'materiel':'enemyFunds';if(b.hp<=0||b.remaining>0){b.fireStatus=b.hp<=0?'Destroyed':'Under construction';continue;}if(!connected){b.fireStatus='Supply cut · firing suspended';continue;}if(b.owner==='red'&&!b.fireTarget){const target=c.units.find(u=>u.side==='blue'&&u.hp>0&&F.distance(b,u)<=d.range);if(target)b.fireTarget={x:target.x,y:target.y};}if(!b.fireTarget){b.fireStatus='Awaiting target';continue;}if(b.cooldown>0){b.fireStatus='Reloading · '+Math.ceil(b.cooldown)+'s';continue;}if(c[pool]<d.ammo){b.fireStatus='Need 18 materiel to fire';continue;}if(c.shells.length>93){b.fireStatus='Awaiting fire slot';continue;}c[pool]-=d.ammo;b.cooldown=d.reload;b.lastFired=c.time;b.fireStatus='Volley fired';b.aim=Math.atan2(b.fireTarget.y-b.y,b.fireTarget.x-b.x);for(let i=0;i<3;i++){const a=i*Math.PI*2/3,tx=b.fireTarget.x+Math.cos(a)*85,ty=b.fireTarget.y+Math.sin(a)*85,flight=2.2+F.distance(b,b.fireTarget)/1000+i*.18;c.shells.push({x:b.x,y:b.y,tx,ty,side:b.owner,remaining:flight,total:flight,damage:48,radius:d.radius});}if(b.owner==='red')b.fireTarget=null;}}
 function step(c,dt){if(c.paused||c.winner)return;dt=F.clamp(dt,0,.1);F.step(c,dt);T.step(c,dt);production(c,dt);batteries(c,dt);c.logisticsClock+=dt;if(c.logisticsClock>=1){logistics(c,c.logisticsClock);c.logisticsClock=0;}c.aiClock+=dt;if(c.aiClock>=12){strategy(c);c.aiClock=0;}
  for(const r of c.regions){const prior=r.owner;r.owner=r.factory.owner;if(r.owner==='blue'&&!r.claimed){r.claimed=true;c.materiel+=r.reward;c.manpower+=20;c.fuel+=15;emit(c,r.name+' secured: stores and recruits recovered.');}for(const b of c.buildings)if(b.regionId===r.id&&b.owner!==r.owner){b.owner=r.owner;b.queue=[];b.repair=false;b.fireTarget=null;}r.factory.production=r.production*(r.supplied?1:.2);}
  const blue=c.regions.filter(r=>r.owner==='blue').length,red=c.regions.filter(r=>r.owner==='red').length;c.score.blue+=blue*dt;c.score.red+=red*dt;
  const required=c.mode==='short'?Math.ceil(c.regions.length*.6):c.regions.length;
  if(blue>=required&&(c.mode==='long'||region(c,'eastwatch').owner==='blue')){c.winner='blue';c.victoryReason='Territorial victory';}else if(!companies(c).length&&!c.buildings.some(b=>b.owner==='blue'&&b.hp>0&&BUILDINGS[b.type].units.length&&at(c,b.x,b.y)?.owner==='blue')){c.winner='red';c.victoryReason='Your field army has been lost';}else if(c.time>=c.elapsedLimit){c.winner=c.score.blue>=c.score.red?'blue':'red';c.victoryReason='Campaign time expired · territory score';}
  Fog.update(c,W);
 }
 function serialize(c){const payload=JSON.parse(JSON.stringify(c,(key,value)=>['map','facilities','territory','_combatIndex'].includes(key)?undefined:value));payload.occupation=c.territory.cells.map(x=>[x.owner,x.value,x.contested]);return JSON.stringify({version:1,payload});}
 function restore(text){const parsed=JSON.parse(text);if(parsed.version!==1||!parsed.payload||parsed.payload.regions?.length!==W.regions.length||!Array.isArray(parsed.payload.units)||!Array.isArray(parsed.payload.buildings))throw Error('This save is not compatible with the grand campaign.');const data=parsed.payload,c=create({faction:data.faction,mode:data.mode});const occupation=data.occupation;delete data.occupation;Object.assign(c,data);c.map=mapFor(c);c.facilities=c.regions.map(r=>r.factory);c.territory=T.create(c,W);if(!Array.isArray(occupation)||occupation.length!==c.territory.cells.length)throw Error('Invalid territory data.');occupation.forEach((v,i)=>{if(!['blue','red','neutral'].includes(v[0])||!Number.isFinite(v[1]))throw Error('Invalid occupation cell.');Object.assign(c.territory.cells[i],{owner:v[0],value:v[1],contested:Boolean(v[2])});});for(const b of c.buildings)if(b.type==='battery'){b.name=BUILDINGS.battery.name;for(const q of b.queue||[]){if(q.cost){const pool=b.owner==='blue'?['materiel','fuel','manpower']:['enemyFunds','enemyFuel','enemyManpower'];pool.forEach((key,i)=>c[key]+=[q.cost.materiel,q.cost.fuel,q.cost.manpower][i]||0);}}b.queue=[];}Fog.update(c,W,true);c.paused=true;return c;}
 return {create,step,region,at,companies,construct,placement,recruit,cancelQueue,upgrade,infrastructure,repair,serialize,restore,spawn,logistics,batteryOrder,BUILDINGS,TROOPS,FACTIONS};
});
