const assert=require('node:assert/strict'),Fog=require('./fog.js');
let count=0;function test(name,fn){fn();count++;console.log('PASS '+name);}
const map={bounds:{minX:0,minY:0,maxX:6000,maxY:6000},coast:[[-100,-100],[6100,6100]],visible(){throw Error('Fog must not use navigation visibility');}};
function state(){return {time:0,units:[{side:'blue',hp:100,x:1100,y:1100},{side:'red',hp:100,x:4100,y:4100}],buildings:[],facilities:[],fog:Fog.create(map)};}
test('Living scouts reveal nearby ground but enemies do not reveal themselves',()=>{const s=state();Fog.update(s,map);assert.ok(Fog.visible(s,1100,1100));assert.ok(Fog.visible(s,1900,1100));assert.equal(Fog.visible(s,4100,4100),false);assert.equal(Fog.explored(s,4100,4100),false);assert.equal(Fog.visible(s,NaN,0),false);assert.equal(Fog.visible(s,-1000,0),false);});
test('Moving or dead scouts leave explored terrain without live visibility',()=>{const s=state();Fog.update(s,map);s.units[0].x=4100;s.units[0].y=4100;s.time=.25;Fog.update(s,map);assert.equal(Fog.visible(s,1100,1100),false);assert.ok(Fog.explored(s,1100,1100));assert.ok(Fog.visible(s,4100,4100));s.units[0].hp=0;s.time=.5;Fog.update(s,map);assert.equal(Fog.visible(s,4100,4100),false);assert.ok(Fog.explored(s,4100,4100));});
test('Refresh cadence is four hertz and unchanged visibility retains its revision',()=>{const s=state();Fog.update(s,map);const revision=s.fog.revision,visible=s.fog.visible;s.time=.1;Fog.update(s,map);assert.equal(s.fog.visible,visible);s.time=.25;Fog.update(s,map);assert.equal(s.fog.revision,revision);s.units[0].hp=0;Fog.update(s,map,true);assert.ok(s.fog.revision>revision);assert.equal(Fog.visible(s,1100,1100),false);});
test('Only completed living friendly buildings and controlled living facilities provide sight',()=>{const s=state();s.units=[];s.buildings=[{owner:'blue',hp:100,remaining:10,x:1100,y:1100},{owner:'red',hp:100,remaining:0,x:4100,y:4100}];s.facilities=[{owner:'blue',hp:100,x:3100,y:1100}];Fog.update(s,map);assert.equal(Fog.visible(s,1100,1100),false);assert.equal(Fog.visible(s,4100,4100),false);assert.ok(Fog.visible(s,3100,1100));s.buildings[0].remaining=0;s.facilities[0].hp=0;Fog.update(s,map,true);assert.ok(Fog.visible(s,1100,1100));assert.equal(Fog.visible(s,1900,1100),false);assert.equal(Fog.visible(s,3100,1100),false);});
test('Fog is JSON compatible and force refresh preserves exploration after loading',()=>{const s=state();Fog.update(s,map);const restored=JSON.parse(JSON.stringify(s));assert.deepEqual(restored.fog,s.fog);restored.units=[];Fog.update(restored,map,true);assert.equal(Fog.visible(restored,1100,1100),false);assert.ok(Fog.explored(restored,1100,1100));assert.ok(Array.isArray(restored.fog.visible));assert.ok(Array.isArray(restored.fog.explored));});
test('Coast outside map bounds fits the fog grid and region factories are supported',()=>{const s=state();delete s.facilities;s.units=[];s.regions=[{factory:{owner:'blue',hp:100,x:-100,y:-100}}];Fog.update(s,map);assert.ok(Fog.visible(s,-100,-100));assert.ok(s.fog.minX<=-100);});
console.log(count+' fog checks passed.');
