const test=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs');
function harness(saved){const elements=new Map(),tasks=[],sent=[],storage=new Map();if(saved)storage.set('living-frontiers-room:ws://localhost/ws',JSON.stringify(saved));function el(id){if(!elements.has(id))elements.set(id,{value:'',checked:false,open:false,children:[],showModal(){this.open=true;},close(){this.open=false;},replaceChildren(){this.children=[];},append(n){this.children.push(n);},addEventListener(type,fn){this['on'+type]=fn;}});return elements.get(id);}class WS{constructor(){WS.latest=this;this.readyState=0;}send(s){sent.push(JSON.parse(s));}close(){this.onclose?.();}open(){this.readyState=1;this.onopen();}receive(m){this.onmessage({data:JSON.stringify(m)});}}
const context={atob:s=>Buffer.from(s,"base64").toString("binary"),window:{},document:{getElementById:el,querySelector(){return null;},createElement:()=>el(Math.random())},URL,location:{href:'http://localhost/',hostname:'localhost'},sessionStorage:{getItem:k=>storage.get(k)||null,setItem:(k,v)=>storage.set(k,v),removeItem:k=>storage.delete(k)},WebSocket:WS,queueMicrotask:fn=>tasks.push(fn),setTimeout:fn=>{tasks.push(fn);return 1;},clearTimeout(){},navigator:{clipboard:{writeText:async()=>{}}}};vm.runInNewContext(fs.readFileSync('multiplayer-client.js','utf8'),context);return{api:context.window.Multiplayer,el,WS,sent,storage,flush(){while(tasks.length)tasks.shift()();}};}
const lobby={type:'lobby',code:'ABCDEF',token:'secret',side:'blue',host:true,status:'playing',players:[{side:'blue',ready:true,connected:true},{side:'red',ready:true,connected:true}]};
test('online menu remains open during subsequent snapshots',()=>{const h=harness();h.el('host-match').onclick();h.WS.latest.open();h.WS.latest.receive(lobby);h.WS.latest.receive({type:'snapshot',snapshot:{}});assert.equal(h.el('multiplayer-menu').open,false);h.api.open();h.WS.latest.receive({type:'snapshot',snapshot:{}});assert.equal(h.el('multiplayer-menu').open,true);});
test('synchronous company actions batch into one packet',()=>{const h=harness();h.el('host-match').onclick();h.WS.latest.open();for(let i=0;i<60;i++)assert.equal(h.api.command({type:'order',ids:['u'+i],order:'move',destination:{x:i,y:i}}),true);h.flush();const commands=h.sent.filter(m=>m.type==='command');assert.equal(commands.length,1);assert.equal(commands[0].commands.length,60);assert.ok(JSON.stringify(commands[0]).length<8192);});
test('expired resumed session clears token and lobby even after prior connection',()=>{const h=harness({code:'ABCDEF',token:'secret'});h.WS.latest.open();h.WS.latest.receive(lobby);h.WS.latest.onclose();h.flush();h.WS.latest.open();h.WS.latest.receive({type:'error',code:'RESUME_EXPIRED',message:'Session unavailable.'});assert.equal(h.api.active,false);assert.equal(h.el('lobby-details').hidden,true);assert.equal(h.storage.size,0);});
const C=require('./campaign.js');
test('compact hydration preserves static geometry and decodes fog and occupation',()=>{const h=harness(),state=C.create({terrainSeed:123}),map=state.map,region=state.regions[0],polygon=region.polygon,factory=region.factory;const packed=Buffer.alloc(state.territory.cells.length*2);for(let i=0;i<state.territory.cells.length;i++){packed[i*2]=i===0?18:1;packed[i*2+1]=i===0?0:255;}const visible=Buffer.alloc(Math.ceil(state.fog.visible.length/8));visible[0]=5;const snapshot={snapshotEncoding:1,terrainSeed:123,time:2,regions:[{id:region.id,owner:'red',factory:{owner:'red',hp:30,capture:0}}],fog:{visible:visible.toString('base64'),explored:visible.toString('base64'),revision:2},occupation:packed.toString('base64')};h.api.mergeSnapshot(state,snapshot);assert.equal(state.map,map);assert.equal(region.polygon,polygon);assert.equal(region.factory,factory);assert.equal(factory.hp,30);assert.ok(Number.isFinite(factory.x));assert.deepEqual(Array.from(state.fog.visible.slice(0,4)),[1,0,1,0]);assert.equal(state.territory.cells[0].owner,'red');assert.equal(state.territory.cells[0].value,-1);assert.equal(state.territory.cells[0].contested,true);assert.equal(state.territory.cells[1].owner,'blue');assert.equal(state.territory.cells[1].value,1);assert.equal(state.facilities[0],factory);assert.equal(state.paused,false);});
test('actual compact snapshots hydrate both commander perspectives',()=>{const M=require('./multiplayer-match.cjs'),match=M.createMatch({terrainSeed:321});for(const side of ['blue','red']){const h=harness(),state=C.create({terrainSeed:321});h.api.mergeSnapshot(state,M.snapshotFor(match,side));assert.ok(state.units.some(u=>u.side==='blue'));assert.ok(state.regions.every(r=>r.polygon.length&&Number.isFinite(r.factory.x)&&r.factory.maxHp>0));assert.ok(state.fog.visible.every(v=>v===0||v===1));assert.equal(state.territory.cells.length,match.territory.cells.length);assert.ok(state.territory.cells.every(c=>['blue','red','neutral'].includes(c.owner)&&Number.isFinite(c.value)));}});
test('expired and ended matches clear resume credentials and leave a usable menu',()=>{for(const message of [{type:'error',code:'ROOM_EXPIRED',message:'Room expired.'},{type:'error',code:'MATCH_ENDED',message:'Match stopped.'}]){const h=harness();h.el('host-match').onclick();h.WS.latest.open();h.WS.latest.receive(lobby);h.WS.latest.receive({type:'snapshot',snapshot:{}});h.WS.latest.receive(message);assert.equal(h.api.active,false);assert.equal(h.storage.size,0);assert.equal(h.el('multiplayer-menu').open,true);}});
test('normal victory retains the room and menu can close with button or Escape',()=>{const h=harness();h.el('host-match').onclick();h.WS.latest.open();h.WS.latest.receive(lobby);h.WS.latest.receive({type:'snapshot',snapshot:{}});h.api.open();assert.equal(h.el('return-match').hidden,false);h.el('return-match').onclick();assert.equal(h.el('multiplayer-menu').open,false);h.api.open();let prevented=false;h.el('multiplayer-menu').oncancel({preventDefault(){prevented=true;}});assert.equal(prevented,false);h.WS.latest.receive({...lobby,status:'ended'});h.WS.latest.receive({type:'snapshot',snapshot:{winner:'blue'}});assert.equal(h.api.active,true);assert.equal(h.storage.size,1);assert.match(h.el('network-status').textContent,/Campaign finished/);});
test('session ending signals game hydration reset',()=>{const h=harness();let resets=0;h.api.onSessionEnded=()=>resets++;h.el('host-match').onclick();h.WS.latest.open();h.WS.latest.receive(lobby);h.WS.latest.receive({type:'error',code:'ROOM_EXPIRED',message:'Room expired.'});assert.equal(resets,1);});
