(()=>{'use strict';
 const $=id=>document.getElementById(id),dialog=$('multiplayer-menu');
 const configured=document.querySelector('meta[name="multiplayer-server"]')?.content;
 const endpoint=new URL(configured||'/ws',location.href);endpoint.protocol=endpoint.protocol==='https:'?'wss:':endpoint.protocol==='http:'?'ws:':endpoint.protocol;
 const storageKey='living-frontiers-room:'+endpoint.href;let socket=null,pending=[],resume=null,retry=null,leaving=false,room=null,connected=false,resumePending=false,matchStarted=false,commands=[],flushPending=false,direct=null,peerBusy=false;
 try{resume=JSON.parse(sessionStorage.getItem(storageKey)||'null');}catch{}
 const api=window.Multiplayer={active:false,onSnapshot:null,onSolo:null,command(command){if(!(direct?direct.connected:connected))return false;commands.push(command);if(!flushPending){flushPending=true;queueMicrotask(()=>{flushPending=false;const batch=commands.splice(0);if(!batch.length)return;while(batch.length){const group=[];while(batch.length&&group.length<60){const candidate=[...group,batch[0]];if(group.length&&JSON.stringify(candidate).length>7000)break;group.push(batch.shift());}send('command',group.length===1?{command:group[0]}:{commands:group});}});}return true;},open(){dialog.showModal();},leave(){peerBusy=false;leaving=true;commands=[];matchStarted=false;resumePending=false;send('leave');direct?.close();direct=null;$('peer-output-area').hidden=true;$('peer-input-area').hidden=true;resume=null;room=null;api.active=false;clearTimeout(retry);try{sessionStorage.removeItem(storageKey);}catch{}socket?.close();socket=null;connected=false;api.onSolo?.();render();}};
 function mergeSnapshot(next,snapshot){
 const selectedRegion=next.selectedRegion,selected=next.selected,occupation=snapshot.occupation;
 for(const [key,value] of Object.entries(snapshot))if(!['map','territory','occupation','regions','fog','selectedRegion','selected'].includes(key))next[key]=value;
 for(const region of snapshot.regions||[]){const existing=next.regions.find(r=>r.id===region.id);if(existing){const polygon=existing.polygon,factory=existing.factory;Object.assign(existing,region);existing.polygon=polygon;Object.assign(factory,region.factory);existing.factory=factory;}}
 if(snapshot.fog){Object.assign(next.fog,snapshot.fog);for(const key of ['visible','explored'])if(typeof next.fog[key]==='string'){const bytes=atob(next.fog[key]);next.fog[key]=Array.from({length:next.fog.cols*next.fog.rows},(_,i)=>(bytes.charCodeAt(i>>3)>>(i%8))&1);}}
 next.selectedRegion=selectedRegion;next.selected=selected;next.paused=false;next.facilities=next.regions.map(r=>r.factory);
 if(typeof occupation==='string'){const bytes=atob(occupation);next.territory.cells.forEach((cell,i)=>{const flag=bytes.charCodeAt(i*2);cell.owner=['neutral','blue','red'][flag&3];cell.contested=Boolean(flag&16);cell.value=bytes.charCodeAt(i*2+1)/127.5-1;});next.territory.revision++;}
 else if(occupation){occupation.forEach((triple,i)=>{const cell=next.territory.cells[i];if(cell)Object.assign(cell,{owner:triple[0],value:triple[1],contested:triple[2]});});next.territory.revision++;}
 return next;
 }
 api.mergeSnapshot=mergeSnapshot;
 function clearSession(){direct?.close();direct=null;peerBusy=false;$('peer-output-area').hidden=true;$('peer-input-area').hidden=true;resume=null;room=null;api.active=false;matchStarted=false;resumePending=false;commands=[];clearTimeout(retry);api.onSessionEnded?.();try{sessionStorage.removeItem(storageKey);}catch{}render();}
 function status(message){$('network-status').textContent=message;}
 function send(type,data={}){if(direct)return direct.send(type,data);if(!connected){status('Connection unavailable. Reconnect or play solo.');return false;}socket.send(JSON.stringify({v:1,type,...data}));return true;}
 function connect(action){if(direct){status('Leave the peer connection before joining a dedicated server.');return;}if(!configured&&location.hostname.endsWith('.github.io')){status('Dedicated server not connected. Use Create peer invite or Join peer invite above to play with a friend.');return;}if(connected){action?.();return;}if(action)pending.push(action);if(socket&&socket.readyState<2)return;leaving=false;status('Connecting…');try{socket=new WebSocket(endpoint.href);}catch{status('Multiplayer unavailable. Run the match server or configure the multiplayer-server endpoint.');return;}
 socket.onopen=()=>{connected=true;status('Connected. Choose a match.');send('hello');if(resume){resumePending=true;send('resume',resume);}else{for(const action of pending.splice(0))action();send('list');}};
 socket.onmessage=e=>{let m;try{m=JSON.parse(e.data);}catch{return;}receiveMessage(m);};
 socket.onclose=()=>{connected=false;socket=null;commands=[];if(leaving)return;status(resume?'Connection lost. Reconnecting…':'Multiplayer unavailable. Start the match server, then try again; solo is available.');if(resume){retry=setTimeout(()=>connect(),2000);matchStarted=false;dialog.showModal();}render();};socket.onerror=()=>status('Cannot reach the match server. Check the server address; solo remains available.');}
 function receiveMessage(m){if(m.type==='lobby'){if(direct){$('peer-output-area').hidden=true;$('peer-input-area').hidden=true;}resumePending=false;room=m;api.active=true;if(m.token){resume={code:m.code,token:m.token};try{sessionStorage.setItem(storageKey,JSON.stringify(resume));}catch{}}status(m.status==='ended'?'Campaign finished. Return to the battlefield to review the result, or leave to play again.':m.status==='playing'?'Match in progress':'Waiting for both commanders to ready.');render();}else if(m.type==='snapshot'){api.active=true;api.onSnapshot?.(m.snapshot);if(!matchStarted){matchStarted=true;if(dialog.open)dialog.close();}$('network-menu').textContent=(direct?'Peer · ':'Online · ')+(room?.code||'match');render();}else if(m.type==='rooms')renderRooms(m.rooms||[]);else if(m.type==='error'){status(m.message);api.onNotice?.(m.message);if(['ROOM_EXPIRED','MATCH_ENDED'].includes(m.code)){clearSession();dialog.showModal();return;}if(resumePending){resumePending=false;resume=null;room=null;api.active=false;matchStarted=false;commands=[];clearTimeout(retry);api.onSessionEnded?.();render();try{sessionStorage.removeItem(storageKey);}catch{}for(const action of pending.splice(0))action();}}}
 function render(){ $('lobby-details').hidden=!room;$('room-code').textContent=room?.code||'';$('room-players').replaceChildren();for(const p of room?.players||[]){const li=document.createElement('li');li.textContent=(p.side===room.side?'You':'Opponent')+' · '+(p.connected?(p.ready?'Ready':'Not ready'):'Disconnected');$('room-players').append(li);}$('ready-match').disabled=!room||!(direct?direct.connected:connected)||room.status!=='waiting';$('ready-match').textContent=room?.players.find(p=>p.side===room.side)?.ready?'Not ready':'Ready';$('start-match').disabled=!room?.host||room.status!=='waiting'||!room.players.every(p=>p.ready&&p.connected)||room.players.length!==2; $('leave-match').hidden=!room&&!resume&&!direct;$('copy-invite').hidden=Boolean(direct);$('peer-host').disabled=Boolean(room)||peerBusy;$('peer-join').disabled=Boolean(room)||peerBusy;$('return-match').hidden=!matchStarted;}
 function renderRooms(rooms){$('public-rooms').replaceChildren();if(!rooms.length)$('public-rooms').textContent='No public rooms yet. Host one to begin.';for(const r of rooms){const b=document.createElement('button');b.textContent=r.code+' · '+r.players+'/2 · '+r.status;b.disabled=r.status!=='waiting'||r.players>=2;b.onclick=()=>send('join',{code:r.code});$('public-rooms').append(b);}}
 $('play-solo').onclick=()=>{if(api.active||resume||direct){api.leave();dialog.close();}else{dialog.close();api.onSolo?.();}};$('host-match').onclick=()=>connect(()=>send('create',{public:$('public-match').checked,mode:'standard'}));$('join-match').onclick=()=>{const code=$('join-code').value.trim().toUpperCase();if(!code){status('Enter the invite code.');return;}connect(()=>send('join',{code}));};$('refresh-rooms').onclick=()=>connect(()=>send('list'));$('ready-match').onclick=()=>send('ready',{ready:!room?.players.find(p=>p.side===room.side)?.ready});$('start-match').onclick=()=>send('start');$('leave-match').onclick=()=>api.leave();$('return-match').onclick=()=>dialog.close();$('copy-invite').onclick=async()=>{try{await navigator.clipboard.writeText(room.code);status('Invite code copied.');}catch{status('Share this invite code: '+room.code);}};$('network-menu').onclick=()=>api.open();dialog.addEventListener('cancel',e=>{if(matchStarted)return;if(api.active||resume||direct)e.preventDefault();else api.onSolo?.();});
 function beginPeer(){
  if(room||api.active){status('Leave the current match before creating another connection.');return false;}
  direct?.close();leaving=true;socket?.close();socket=null;connected=false;resume=null;pending=[];clearTimeout(retry);try{sessionStorage.removeItem(storageKey);}catch{}
  api.onSessionEnded?.();matchStarted=false;
  direct=PeerSession.create({onMessage:receiveMessage,onStatus:status,onSignal:(text,kind)=>{
   $('peer-output').value=text;$('peer-output-area').hidden=false;$('peer-output-label').textContent=kind==='invite'?'1. Send this invite to your friend':'2. Send this reply back to the host';
   $('peer-input-area').hidden=kind!=='invite';$('peer-input').value='';$('peer-input-label').textContent='2. Paste your friend’s reply';$('peer-apply').textContent='Connect to friend';
   status(kind==='invite'?'Invite ready. Keep this tab open and paste your friend’s reply below.':'Reply ready. Send it to the host and keep this tab open.');render();
  }});render();return true;
 }
 async function peerAction(action){const connection=direct;peerBusy=true;$('peer-host').disabled=true;$('peer-join').disabled=true;$('peer-apply').disabled=true;try{await action();}catch(error){if(direct===connection){status(error.message);direct?.close();direct=null;api.onSessionEnded?.();}}finally{if(!direct||direct===connection){peerBusy=false;$('peer-apply').disabled=false;render();}}}
 $('peer-host').onclick=()=>{if(!beginPeer())return;$('peer-input-area').hidden=true;$('peer-output-area').hidden=true;status('Creating invite and discovering a direct connection…');peerAction(()=>direct.host());};
 $('peer-join').onclick=()=>{if(room||api.active){status('Leave the current match first.');return;}direct?.close();direct=null;$('peer-output-area').hidden=true;$('peer-input-area').hidden=false;$('peer-input').value='';$('peer-input-label').textContent='1. Paste the host’s invite';$('peer-apply').textContent='Create reply';status('Ask your friend to create an invite, then paste it here.');render();};
 $('peer-apply').onclick=()=>{const text=$('peer-input').value.trim();if(!text){status('Paste the complete invite or reply first.');return;}if(direct?.isHost){status('Connecting to your friend…');peerAction(()=>direct.accept(text));}else if(beginPeer()){status('Creating your connection reply…');peerAction(()=>direct.join(text));}};
 $('peer-copy').onclick=async()=>{try{await navigator.clipboard.writeText($('peer-output').value);status('Connection text copied. Send it privately to your friend.');}catch{status('Select the connection text and copy it manually.');}};
 render();dialog.showModal();if(resume)connect();
})();
