const assert=require('node:assert/strict'),F=require('./simulation.js'),C=require('./campaign.js');
let passed=0;function test(name,run){run();passed++;console.log('PASS '+name)}
function state(){const s=F.create();s.units=[F.formation('a','A','blue','infantry',100,100)];s.units[0].speed=100;s.map={route:(a,b)=>[{x:b.x,y:b.y}],walkable:()=>true,visible:()=>true,terrain:()=> 'open',revision:()=>''};return s;}
test('Queued moves leave the active route intact and execute in order',()=>{const s=state(),u=s.units[0];F.command(s,'a','move',{x:200,y:100});F.command(s,'a','move',{x:300,y:100},{queue:true});assert.equal(u.path.at(-1).x,200);assert.equal(u.commandQueue.length,1);for(let i=0;i<100;i++)F.step(s,.05);assert.equal(u.x,300);assert.equal(u.commandQueue.length,0)});
test('Queue validation starts at the last queued destination',()=>{const s=state(),origins=[];s.map.route=(a,b)=>{origins.push(a.x);return [{...b}]};F.command(s,'a','move',{x:200,y:100});F.command(s,'a','move',{x:300,y:100},{queue:true});F.command(s,'a','advance',{x:400,y:100},{queue:true});assert.deepEqual(origins,[100,200,300]);assert.equal(s.units[0].commandQueue[1].order,'advance')});
test('Invalid replacement and invalid queued destination preserve existing orders',()=>{const s=state(),u=s.units[0];F.command(s,'a','move',{x:200,y:100});F.command(s,'a','move',{x:300,y:100},{queue:true});s.map.route=()=>[];assert.equal(F.command(s,'a','move',{x:500,y:100}),false);assert.equal(F.command(s,'a','move',{x:500,y:100},{queue:true}),false);assert.equal(u.path.at(-1).x,200);assert.equal(u.commandQueue.length,1)});
test('Fresh moves, hold and retreat cancel previous waypoints',()=>{for(const order of ['move','hold','repair']){const s=state(),u=s.units[0];F.command(s,'a','move',{x:200,y:100});F.command(s,'a','move',{x:300,y:100},{queue:true});assert(F.command(s,'a',order,{x:400,y:100}));assert.equal(u.commandQueue.length,0)}});
test('Broken queued crossing waits without repeated searches and resumes after repair',()=>{const s=state(),u=s.units[0];let broken=false,calls=0;s.map.revision=()=>broken?'broken':'open';s.map.route=(a,b)=>{calls++;return broken&&b.x===300?[]:[{...b}]};F.command(s,'a','move',{x:101,y:100});F.command(s,'a','move',{x:300,y:100},{queue:true});broken=true;for(let i=0;i<30;i++)F.step(s,.05);assert.equal(u.commandQueue.length,1);const before=calls;for(let i=0;i<20;i++)F.step(s,.05);assert.equal(calls,before);broken=false;for(let i=0;i<100;i++)F.step(s,.05);assert.equal(u.x,300)});
test('Queues are capped and survive campaign saves',()=>{const s=C.create(),u=s.units.find(u=>u.side==='blue'),p={x:u.x+50,y:u.y};assert(F.command(s,u.id,'move',p));for(let i=0;i<32;i++)assert(F.command(s,u.id,'move',p,{queue:true}));assert.equal(F.command(s,u.id,'move',p,{queue:true}),false);const restored=C.restore(C.serialize(s));assert.deepEqual(restored.units.find(v=>v.id===u.id).commandQueue,u.commandQueue)});
test('Dragged formations use unique evenly spaced positions along the chosen line',()=>{const units=[{id:'a',x:0,y:0},{id:'b',x:100,y:0},{id:'c',x:200,y:0}],p=F.formationPlan(units,{x:0,y:400},{x:300,y:400});assert.deepEqual(p.map(s=>s.goal),[{x:0,y:400},{x:150,y:400},{x:300,y:400}]);assert.equal(new Set(p.map(s=>s.id)).size,3)});
test('Single-company orders use the clicked destination; compact groups keep spacing',()=>{assert.deepEqual(F.formationPlan([{id:'a',x:7,y:9}],{x:120,y:150})[0].goal,{x:120,y:150});const p=F.formationPlan([{id:'a',x:0,y:0},{id:'b',x:1,y:1}],{x:120,y:150});assert(F.distance(p[0].goal,p[1].goal)>=75)});
console.log(passed+' army control checks passed.');
