const assert=require('node:assert/strict'),W=require('./world.js'),P=require('./projection.js'),C=require('./campaign.js'),F=require('./simulation.js');
let count=0;function test(name,fn){fn();count++;console.log('PASS '+name);}
const map=W.withTerrain(823901),points=[];
for(let y=W.bounds.minY;y<W.bounds.maxY;y+=240)for(let x=W.bounds.minX;x<W.bounds.maxX;x+=240)if(W.walkable(x,y))points.push({x,y});
test('Seeded hills repeat exactly and different seeds change the landscape',()=>{const same=W.withTerrain(823901),other=W.withTerrain(42);let changed=0;const classes=new Set();for(const p of points){assert.equal(map.height(p.x,p.y),same.height(p.x,p.y));assert.equal(map.terrain(p.x,p.y),same.terrain(p.x,p.y));if(Math.abs(map.height(p.x,p.y)-other.height(p.x,p.y))>10)changed++;classes.add(map.terrain(p.x,p.y));}assert.ok(changed>points.length/2);for(const t of ['hill','ridge','valley','forest'])assert.ok(classes.has(t));assert.equal(W.terrainSeed,null);assert.ok(map.bytes<200000);});
test('Projected terrain remains single-valued with accurate picking at all zoom levels',()=>{for(const p of points){const g=map.gradient(p.x,p.y);assert.ok(Math.abs(g.x)+Math.abs(g.y)<.55);for(const scale of [.19,1.1,10]){const q=P.project(p.x,p.y,undefined,map),offset={x:-1250,y:340};const actual=P.unproject(q.x*scale+offset.x,q.y*scale+offset.y,scale,offset,map);assert.ok(Math.hypot(actual.x-p.x,actual.y-p.y)<.001);}}});
test('New terrain keeps spawns, roads and crossings connected',()=>{const c=C.create({terrainSeed:823901});for(const u of c.units)assert.ok(c.map.walkable(u.x,u.y));for(const link of W.roadLinks){const a=C.region(c,link.from),b=C.region(c,link.to);assert.deepEqual(c.map.route(a,b),W.route(a,b));}for(const y of W.bridges)assert.ok(c.map.walkable(W.riverX(y),y));});
test('Save restoration keeps exact elevation without serializing height arrays',()=>{const c=C.create({terrainSeed:823901}),save=C.serialize(c),restored=C.restore(save);assert.equal(restored.terrainSeed,823901);assert.ok(!save.includes('terrainMap'));for(const p of points)assert.equal(restored.map.height(p.x,p.y),map.height(p.x,p.y));});
test('Legacy saves retain their old terrain and invalid seeds are rejected',()=>{const data=JSON.parse(C.serialize(C.create()));delete data.payload.terrainSeed;delete data.payload.terrainVersion;const old=C.restore(JSON.stringify(data));for(const p of points)assert.equal(old.map.height(p.x,p.y),W.height(p.x,p.y));for(const seed of [-1,1.5,4294967296,'12'])assert.throws(()=>C.create({terrainSeed:seed}));assert.equal(C.create({terrainSeed:0}).terrainSeed,0);});
let blocked;
for(const p of points){const b={x:p.x+240,y:p.y};if(W.walkable(b.x,b.y)&&!map.lineOfFire(p,b)){blocked=[p,b];break;}}
test('Real generated crests block direct line of fire',()=>{assert.ok(blocked);assert.equal(map.lineOfFire(blocked[0],blocked[1]),false);assert.equal(map.lineOfFire(blocked[1],blocked[0]),false);assert.equal(map.lineOfFire(blocked[0],blocked[0]),true);});
function duel(terrain='open',artillery=false){const s=F.create();s.map={...map,terrain:()=>terrain};s.units=[F.formation('a','Attacker','blue',artillery?'artillery':'tank',blocked[0].x,blocked[0].y),F.formation('b','Defender','red','tank',blocked[1].x,blocked[1].y)];for(const u of s.units){u.range=500;u.aiTimer=100;u.damage=10;}return s;}
test('Ridge occlusion stops direct-fire damage and tells the player why',()=>{const s=duel(),hp=s.units[1].hp;F.step(s,.1);assert.equal(s.units[1].hp,hp);assert.match(s.units[0].status,/Ridge blocks/);assert.equal(s.shots.length,0);});
test('Artillery still fires over the same generated ridge',()=>{const s=duel('open',true);s.shells=[];s.explosions=[];s.craters=[];F.step(s,.1);assert.equal(s.shells.length,1);assert.equal(s.shells[0].side,'blue');});
test('Ridge cover reduces actual direct-fire damage by twenty percent',()=>{const open=duel('open'),ridge=duel('ridge');for(const s of [open,ridge])s.map.lineOfFire=()=>true;const hp=open.units[1].hp;F.step(open,.1);F.step(ridge,.1);assert.ok(Math.abs((hp-ridge.units[1].hp)/(hp-open.units[1].hp)-.8)<1e-9);});
console.log(count+' terrain checks passed.');
