const assert=require('node:assert/strict'),C=require('./campaign.js'),T=require('./territory.js'),F=require('./simulation.js');
let count=0;function test(name,fn){fn();count++;console.log('PASS '+name);}function tick(c,seconds){for(let i=0;i<seconds*4;i++)T.step(c,.25);}
test('Occupation persists after troops leave and changes back only under enemy pressure',()=>{const c=C.create(),u=c.units[0];c.units=[u];Object.assign(u,{x:C.region(c,'pinewood').x,y:C.region(c,'pinewood').y});const cells=c.territory.cells.filter(x=>x.region==='pinewood');tick(c,15);const gained=cells.filter(x=>x.owner==='blue').length;assert.ok(gained>0);c.units=[];tick(c,30);assert.equal(cells.filter(x=>x.owner==='blue').length,gained);c.units=[{...u,side:'red'}];tick(c,25);assert.ok(cells.filter(x=>x.owner==='blue').length<gained);});
test('Opposing troops contest ground and visibly block the town capture',()=>{const c=C.create(),u=c.units[0];Object.assign(u,{x:C.region(c,'pinewood').x,y:C.region(c,'pinewood').y});c.units=[u,{...u,id:'test-enemy',side:'red'}];tick(c,12);const r=C.region(c,'pinewood');assert.match(r.captureStatus,/Contested/);assert.equal(r.factory.owner,'neutral');assert.ok(c.territory.cells.some(x=>x.contested));});
test('Town capture requires ground and occupancy; recapture never grants a second reward',()=>{const c=C.create(),u=c.units[0],r=C.region(c,'pinewood');c.units=[u];Object.assign(u,{x:r.x,y:r.y});tick(c,20);assert.equal(r.factory.owner,'blue');C.step(c,.05);assert.ok(r.claimed);c.units=[{...u,side:'red'}];tick(c,30);assert.equal(r.factory.owner,'red');const money=c.materiel;c.units=[u];tick(c,30);C.step(c,.05);assert.equal(r.factory.owner,'blue');assert.ok(c.materiel-money<1);});
test('Camera-independent movement accelerates, turns gradually, and stops at its destination',()=>{const c=C.create(),u=c.units[0];c.units=[u];const start={x:u.x,y:u.y},target={x:u.x-150,y:u.y};F.command(c,u.id,'move',target);const angle=u.angle;F.step(c,.05);const first=F.distance(start,u);assert.ok(first>0&&first<u.speed*.05);assert.ok(Math.abs(u.angle-angle)<=3.6*.05+.001);let old={x:u.x,y:u.y};F.step(c,.05);assert.ok(F.distance(old,u)>first);for(let i=0;i<200;i++)F.step(c,.05);assert.ok(F.distance(u,target)<.1);assert.equal(u.velocity,0);});
test('Stationary influence reuses visibility; moving troops invalidate their footprint',()=>{const c=C.create(),u=c.units[0];c.units=[u];let calls=0;const map=c.map;c.map={...map,visible:(a,b)=>{calls++;return map.visible(a,b);}};T.step(c,.25);const first=calls;assert.ok(first>0);T.step(c,.25);assert.equal(calls,first);u.x+=90;T.step(c,.25);assert.ok(calls>first);});
test('Unchanged territory does not request a frontline rebuild',()=>{const c=C.create();c.units=[];const revision=c.territory.revision;tick(c,10);assert.equal(c.territory.revision,revision);const u=C.create().units[0];u.x=C.region(c,'pinewood').x;u.y=C.region(c,'pinewood').y;c.units=[u];tick(c,15);assert.ok(c.territory.revision>revision);const changed=c.territory.revision;c.units=[];tick(c,10);assert.equal(c.territory.revision,changed);});
test('Neutral militia defend without claiming enemy territory',()=>{const c=C.create();c.units=c.units.filter(u=>u.militia);tick(c,30);assert.ok(c.regions.filter(r=>r.owner==='neutral').length===21);assert.ok(c.territory.cells.filter(x=>x.owner==='red').every(x=>c.regions.find(r=>r.id===x.region).owner==='red'));});
console.log(count+' occupation and movement checks passed.');
