/* Original visual study. Scripted animation, not a replacement game simulation. */
(() => {
'use strict';
const W=World.withTerrain(823901),S=W.SCALE,canvas=document.querySelector('#scene'),ctx=canvas.getContext('2d');
const $=id=>document.getElementById(id),reduce=matchMedia('(prefers-reduced-motion: reduce)');
const region=W.regions.find(r=>r.id==='greywater'),hub={x:region.x,y:region.y},focus={x:hub.x+220,y:hub.y+210};
const P=(x,y,z)=>Projection.project(x,y,z,W),TAU=Math.PI*2;
let width=1440,height=900,zoom=3.1,offset={x:0,y:0},camera=null,last=0,t=0,running=!reduce.matches,dirty=true,drag=null,view='battle',front=0,pushUntil=0,lastAuto=0,showCover=true,showFog=true;
let seed=1709;const rand=()=>{seed=(Math.imul(seed,1664525)+1013904223)>>>0;return seed/4294967296},clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const base=document.createElement('canvas');base.width=3200;base.height=1800;const ground=base.getContext('2d');
const trees=[],buildings=[],units=[],shells=[],effects=[],craters=[],roads=[];
const canSee=o=>!showFog||o.x<hub.x+970;
const grass=new Path2D();let labelCameraKey='',lastMetrics='';
function shape(c,points,fill,stroke,line=1){c.beginPath();points.forEach((p,i)=>i?c.lineTo(p.x,p.y):c.moveTo(p.x,p.y));c.closePath();if(fill){c.fillStyle=fill;c.fill()}if(stroke){c.strokeStyle=stroke;c.lineWidth=line;c.stroke()}}
function line(c,points,color,size,dash=[]){c.beginPath();points.forEach((p,i)=>i?c.lineTo(p.x,p.y):c.moveTo(p.x,p.y));c.strokeStyle=color;c.lineWidth=size;c.lineJoin='round';c.lineCap='round';c.setLineDash(dash);c.stroke();c.setLineDash([])}
function points(world){return world.map(p=>P(p.x,p.y))}
function groundRect(c,x,y,w,d,fill,stroke){shape(c,points([{x,y},{x:x+w,y},{x:x+w,y:y+d},{x,y:y+d}]),fill,stroke,.35)}
function ellipse(c,p,rx,ry,fill){c.beginPath();c.ellipse(p.x,p.y,rx,ry,0,0,TAU);c.fillStyle=fill;c.fill()}
function makeBase(){ground.setTransform(.5,0,0,.5,0,0);ground.clearRect(0,0,6400,3600);const coast=W.coast.map(([x,y])=>P(x,y));shape(ground,coast,'#7a8260','#b4b58f',19);ground.save();shape(ground,coast);ground.clip();
 TerrainArt.paint(ground,W,P);
 for(const r of W.regions){for(let i=0;i<13;i++){const x=r.x-750+rand()*1450,y=r.y-650+rand()*1300,w=120+rand()*180,d=85+rand()*220;if(!W.walkable(x,y)||W.terrain(x,y)==='forest')continue;groundRect(ground,x,y,w,d,['#8c8c61','#999267','#687957','#9a956c','#777c54'][i%5],'#586c5080');for(let n=10;n<d;n+=18)line(ground,points([{x:x+5,y:y+n},{x:x+w-5,y:y+n}]),'#444e3224',.6)}
  for(let i=0;i<(r.id===region.id?0:10);i++){const x=r.x+(i%4-1.5)*95,y=r.y+120+Math.floor(i/4)*110;if(W.walkable(x,y))buildings.push({x,y,w:38+rand()*25,d:35+rand()*25,h:22+rand()*16,kind:'house'})}}
 const river=[];for(let y=140*S;y<3200*S;y+=18*S)river.push(P(W.riverX(y),y,2*S));line(ground,river,'#575e4b',82);line(ground,river,'#87967f',73);line(ground,river,'#4c7472',65);line(ground,river,'#638a80',45);line(ground,river,'#819e8c55',1.1);
 for(const road of W.roads){const p=[];for(let i=1;i<road.length;i++){const a=road[i-1],b=road[i],n=Math.max(1,Math.ceil(Math.hypot(a.x-b.x,a.y-b.y)/80));for(let j=0;j<=n;j++)p.push(P(a.x+(b.x-a.x)*j/n,a.y+(b.y-a.y)*j/n))}roads.push(p);line(ground,p,'#46514566',7);line(ground,p,'#b2a17d',4);line(ground,p,'#c4b28c77',.7)}
 for(let i=0;i<11000;i++){const x=(220+rand()*4200)*S,y=(200+rand()*2850)*S;if(W.terrain(x,y)!=='forest')continue;const tree={x,y,size:25+rand()*23};trees.push(tree);ellipse(ground,P(x,y),3,2,'#344e39')}
 for(let i=0;i<2300;i++){const x=hub.x-1100+rand()*2300,y=hub.y-800+rand()*2100;if(!W.walkable(x,y)||(x>hub.x-330&&x<hub.x+340&&y>hub.y-300&&y<hub.y+250))continue;const p=P(x,y);grass.moveTo(p.x-1,p.y);grass.lineTo(p.x,p.y-1.3);grass.lineTo(p.x+.7,p.y);}
 // Authored industrial yard and lanes distinguish this region from farmland.
 groundRect(ground,hub.x-310,hub.y-290,650,530,'#6d715d','#ac9f7a');
 for(let i=0;i<5;i++)line(ground,points([{x:hub.x-280,y:hub.y+140+i*15},{x:hub.x+310,y:hub.y+140+i*15}]),i%2?'#555a4a':'#a79d7c',.6);
 for(let i=0;i<160;i++){const a=rand()*TAU,r=450+rand()*350,x=hub.x+700+Math.cos(a)*r*.65,y=hub.y-280+Math.sin(a)*r;if(W.walkable(x,y)){trees.push({x,y,size:30+rand()*24});ellipse(ground,P(x,y),3,2,'#3d563d')}}
 ground.restore();
 for(let i=0;i<3;i++)buildings.push({x:hub.x-150+i*130,y:hub.y-70,w:105,d:140,h:52,kind:'factory'});
 buildings.push({x:hub.x-230,y:hub.y-205,w:45,d:45,h:130,kind:'stack'},{x:hub.x+200,y:hub.y-205,w:46,d:46,h:105,kind:'stack'});
 for(let i=0;i<7;i++)buildings.push({x:hub.x-590+(i%3)*110,y:hub.y+200+Math.floor(i/3)*120,w:46+rand()*18,d:45+rand()*20,h:32+rand()*12,kind:'house'});
 for(let i=0;i<3;i++)buildings.push({x:hub.x+90+i*62,y:hub.y-215,w:46,d:46,h:46,kind:'tank'});
 for(const o of [...trees,...buildings]){const p=P(o.x,o.y);o.px=p.x;o.py=p.y}
 for(let i=0;i<8;i++)units.push({x:hub.x-120+(i%2)*85,y:hub.y+350+Math.floor(i/2)*76,kind:i<4?'tank':'mech',side:'blue',angle:-.2});
 for(let i=0;i<24;i++)units.push({x:hub.x+225+(i%8)*20,y:hub.y+275+Math.floor(i/8)*33,kind:'soldier',side:'blue',angle:0});
 for(let i=0;i<18;i++)units.push({x:hub.x+620+(i%6)*24,y:hub.y+50+Math.floor(i/6)*40,kind:'soldier',side:'red',angle:Math.PI});
 for(let i=0;i<3;i++)units.push({x:hub.x+750,y:hub.y+100+i*95,kind:'tank',side:'red',angle:Math.PI});
}
const modelRenderer=FrontierModels.createRenderer();
function model(type,o,options={}){const p=P(o.x,o.y);modelRenderer.draw(ctx,type,p.x,p.y,1/S,{side:o.side||'neutral',angle:o.angle||0,turret:o.angle||0,detail:zoom>1.1,...options});}
function building(o){model(o.kind==='factory'?'industry':o.kind==='tank'?'tank-store':o.kind,o,{w:o.w,d:o.d,h:o.h});}
function tree(o){model(Math.floor(o.x+o.y)%3===0?'pine':'tree',o,{w:65,d:60,h:Math.round(o.size/4)*4});}
function vehicle(o){model(o.kind,o,{w:36,d:20,h:21});}
function soldier(o){model('infantry',o,{w:8,d:7,h:11,pose:front>20?'march':'stand'});}
function trench(){model('trench',{x:hub.x+295,y:hub.y+280},{w:290,d:48,h:8});}
function screen(p){const q=P(p.x,p.y,p.z);return {x:q.x*zoom+offset.x,y:q.y*zoom+offset.y}}
function onScreen(o,margin=100){const p=o.px===undefined?screen(o):{x:o.px*zoom+offset.x,y:o.py*zoom+offset.y};return p.x> -margin&&p.x<width+margin&&p.y> -margin&&p.y<height+margin}
function unitIcon(p,kind,side,selected=false){const q=screen(p),color=side==='blue'?'#96d4cd':'#e6a186';ctx.save();ctx.translate(q.x,q.y-16);ctx.fillStyle='#22372f';ctx.strokeStyle=selected?'#f1d58f':color;ctx.lineWidth=selected?2:1;ctx.fillRect(-15,-10,30,20);ctx.strokeRect(-15,-10,30,20);ctx.strokeStyle=color;ctx.lineWidth=1.5;if(kind==='tank'){ctx.beginPath();ctx.ellipse(0,0,8,4,0,0,TAU);ctx.stroke()}else{line(ctx,[{x:-8,y:-5},{x:8,y:5}],color,1.3);line(ctx,[{x:-8,y:5},{x:8,y:-5}],color,1.3)}ctx.restore()}
function addEffect(x,y,big=true){if(effects.length>=48)effects.shift();effects.push({x,y,born:t,big,seed:rand()*TAU});if(big){if(craters.length>=32)craters.shift();craters.push({x,y,size:24+rand()*10})}}
function salvo(){for(let i=0;i<3;i++){if(shells.length>=12)break;shells.push({x:hub.x-340,y:hub.y+650,tx:hub.x+600+i*80,ty:hub.y+120+(i%2)*90,start:t+i*.22,duration:1.3+i*.1})}running=true;$('motion').textContent='Pause effects';$('motion').setAttribute('aria-pressed','true');wake()}
function drawEffects(){for(const e of effects){const age=t-e.born;if(age>2.7||age<0||!onScreen(e)||!canSee(e))continue;const p=P(e.x,e.y),size=e.big?20:5;
 if(age<.09&&!reduce.matches){ellipse(ctx,p,size*(.5+age*10),size*.6,'#fff3b4');ellipse(ctx,p,size*.35,size*.25,'#fffbe4')}
 if(age<.45&&!reduce.matches){for(let i=0;i<8;i++){const a=e.seed+i*TAU/8,r=age*size*2.7,q={x:p.x+Math.cos(a)*r,y:p.y+Math.sin(a)*r*.5-Math.sin(age*5)*size*.6};ellipse(ctx,q,(1-age*1.5)*3,2,['#bd9b69','#7a7756','#e1be7d'][i%3])}}
 for(let i=0;i<(e.big?5:2);i++){const k=clamp((age-.05-i*.035)/2.5,0,1);if(!k)continue;ctx.globalAlpha=(1-k)*.47;const q={x:p.x+(i-2)*size*.3+k*size*.5,y:p.y-k*size*1.3-i*1.5};ellipse(ctx,q,size*(.3+k*.7),size*(.24+k*.6),i%2?'#777768':'#515e50')}ctx.globalAlpha=1;
 }
 for(const s of shells){const k=(t-s.start)/s.duration;if(k<0||k>1)continue;const x=s.x+(s.tx-s.x)*k,y=s.y+(s.ty-s.y)*k,z=W.height(x,y)+Math.sin(k*Math.PI)*220,p=P(x,y,z),q=P(x-(s.tx-s.x)*.02,y-(s.ty-s.y)*.02,z-8);if(canSee({x,y})&&onScreen({x,y},150))line(ctx,[q,p],'#ffe3a0',1.5/zoom)}
 if(running&&!reduce.matches&&zoom>.7){for(let i=0;i<3;i++){const k=(t*.8+i*.32)%1;if(k>.09)continue;const a=P(hub.x+300+i*23,hub.y+285,W.height(hub.x+300,hub.y+285)+8),b=P(hub.x+590+i*21,hub.y+115);line(ctx,[a,{x:a.x+(b.x-a.x)*.75,y:a.y+(b.y-a.y)*.75}],'#f5ddb17a',.8/zoom);ellipse(ctx,a,2,1,'#fff0b5')}}
 for(const b of buildings.filter(b=>b.kind==='stack')){if(!onScreen(b)||!canSee(b))continue;for(let i=0;i<4;i++){const k=(t*.14+i*.25)%1,p=P(b.x+k*80,b.y-5,W.height(b.x,b.y)+b.h+k*90);ctx.globalAlpha=(1-k)*.14;ellipse(ctx,p,3+k*9,2+k*5,'#c9c7af')}ctx.globalAlpha=1}
}
const labels=[{x:hub.x-80,y:hub.y-50,z:W.height(hub.x,hub.y)+70,title:'Greywater steelworks',detail:'Industrial district / production active'},{x:hub.x+300,y:hub.y+280,title:'Entrenched infantry',detail:'Cover active: -50% incoming damage',kind:'cover'},{x:hub.x+660,y:hub.y+60,title:'Eastern defenders',detail:'Contested ground',kind:'enemy'}];
for(const l of labels){const el=document.createElement('div');el.className='map-label '+(l.kind||'');el.innerHTML=l.title+'<small>'+l.detail+'</small>';$('world-labels').appendChild(el);l.el=el}
function draw(){const dpr=Math.min(devicePixelRatio||1,1.5);ctx.setTransform(dpr,0,0,dpr,0,0);const sea=ctx.createLinearGradient(0,0,0,height);sea.addColorStop(0,'#4b6965');sea.addColorStop(1,'#314e4a');ctx.fillStyle=sea;ctx.fillRect(0,0,width,height);ctx.save();ctx.translate(offset.x,offset.y);ctx.scale(zoom,zoom);ctx.drawImage(base,0,0,6400,3600);if(zoom>.75){ctx.strokeStyle='#cad19b20';ctx.lineWidth=.45;ctx.stroke(grass);for(const road of roads){if(!road.some(p=>p.x*zoom+offset.x> -50&&p.x*zoom+offset.x<width+50&&p.y*zoom+offset.y> -50&&p.y*zoom+offset.y<height+50))continue;line(ctx,road,'#776f5377',4.8);line(ctx,road,'#b6a67f',2.6);}}
 const macro=clamp((.75-zoom)/.45,0,1);for(const r of W.regions){const p=r.polygon.map(([x,y])=>P(x,y));if(macro){ctx.globalAlpha=macro*.53;shape(ctx,p,r.owner==='blue'?'#6cbcb7':r.owner==='red'?'#b57356':'#d2c38d');ctx.globalAlpha=1}line(ctx,[...p,p[0]],r.id===region.id?'#e1ca87':macro?'#cdd2ad66':'#e0dbb02e',(r.id===region.id?1.8:.65)/zoom)}
 const frontline=[];for(let i=-14;i<=14;i++){const y=hub.y+i*90,x=hub.x+540+Math.sin(i*.53)*85+front;frontline.push(P(x,y))}line(ctx,frontline,'#172f2655',6/zoom);line(ctx,frontline,'#e7cf99',1.4/zoom);line(ctx,frontline,'#b57853',.6/zoom);
 for(const c of craters){if(!onScreen(c)||!canSee(c))continue;const p=P(c.x,c.y);ellipse(ctx,p,c.size/S,c.size*.55/S,'#313d3090');ellipse(ctx,{x:p.x-1,y:p.y-1},c.size*.65/S,c.size*.3/S,'#172e267a')}
 if(zoom>.55){trench();const objects=[...buildings.filter(o=>onScreen(o)&&canSee(o)),...trees.filter(o=>onScreen(o)&&canSee(o)),...units.map(u=>({...u,x:u.x+(u.side==='blue'?front*.65:0)})).filter(o=>onScreen(o)&&canSee(o))].sort((a,b)=>a.x+a.y-b.x-b.y);for(const o of objects){if(o.size)tree(o);else if(o.kind==='soldier'){if(zoom>1.1)soldier(o)}else if(o.kind==='tank'||o.kind==='mech'){if(o.side)vehicle(o);else building(o)}else building(o)}}
 drawEffects();
 if(showFog){const a=P(hub.x+970,hub.y-1800),b=P(hub.x+970,hub.y+2200),c=P(hub.x+4800,hub.y+2200),d=P(hub.x+4800,hub.y-1800);shape(ctx,[a,b,c,d],'#243a3655')}
 ctx.restore();
 if(zoom<.7){for(const r of W.regions){const p=screen(r);if(p.x<40||p.x>width-40||p.y<190||p.y>height-190)continue;ctx.font=r.id===region.id?'bold 12px Trebuchet MS':'10px Trebuchet MS';ctx.textAlign='center';ctx.fillStyle=r.id===region.id?'#fff0c4':'#e4e2c9';ctx.fillText(r.name,p.x,p.y)}unitIcon({x:hub.x+250+front*.65,y:hub.y+350},'tank','blue',true);unitIcon({x:hub.x+680,y:hub.y+80},'infantry','red')}
 else{unitIcon({x:hub.x-60+front*.65,y:hub.y+400},'tank','blue',true);unitIcon({x:hub.x+300+front*.65,y:hub.y+330},'infantry','blue');if(!showFog||front>0)unitIcon({x:hub.x+760,y:hub.y+200},'tank','red')}
 const labelKey=[zoom,offset.x,offset.y,showCover,showFog,width,height,front>20,front].join(',');if(labelKey!==labelCameraKey){labelCameraKey=labelKey;for(const l of labels){const anchor=l.kind==='cover'?{...l,x:l.x+front*.65}:l,p=screen(anchor);if(l.kind==='cover'){const content=front>20?'Advancing infantry<small>Outside trench / cover lost</small>':l.title+'<small>'+l.detail+'</small>';if(l.el.innerHTML!==content)l.el.innerHTML=content;}l.el.hidden=!canSee(anchor)||zoom<.9||p.x<30||p.x>width-40||p.y<170||p.y>height-180||(l.kind==='cover'&&!showCover);if(!l.el.hidden){l.el.style.left=p.x+'px';l.el.style.top=p.y+'px'}}}
 const metrics=`${view[0].toUpperCase()+view.slice(1)} view / ${effects.length} impact effects / scripted prototype`;if(metrics!==lastMetrics){lastMetrics=metrics;$('metrics').textContent=metrics}
}
function go(mode,instant=false){instant=instant||reduce.matches;view=mode;let target=mode==='country'?{x:2350*S,y:1580*S}:mode==='region'?{x:hub.x+180,y:hub.y+120}:focus;const desired=mode==='country'?Math.min((width-100)/6100,(height-250)/2700):mode==='region'?Math.min(width/1700,height/950):Math.min(width/510,height/310);const p=P(target.x,target.y),to={zoom:desired,x:width*.48-p.x*desired,y:height*.47-p.y*desired};if(instant){zoom=to.zoom;offset={x:to.x,y:to.y};camera=null}else camera={from:{zoom,x:offset.x,y:offset.y},to,start:performance.now()};document.querySelectorAll('[data-view]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.view===mode)));wake()}
function resize(){width=canvas.clientWidth;height=canvas.clientHeight;const dpr=Math.min(devicePixelRatio||1,1.5);canvas.width=Math.round(width*dpr);canvas.height=Math.round(height*dpr);go(view,true)}
document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>go(b.dataset.view));$('salvo').onclick=salvo;$('advance').onclick=()=>{pushUntil=t+5;running=true;$('motion').textContent='Pause effects';$('motion').setAttribute('aria-pressed','true');wake()};$('cover').onclick=()=>{showCover=!showCover;$('cover').setAttribute('aria-pressed',String(showCover));$('cover-text').textContent=showCover?(front>20?'Infantry advancing / cover lost':'Infantry cover: -50% damage'):'Cover overlay hidden';wake()};$('fog').onclick=()=>{showFog=!showFog;$('fog').setAttribute('aria-pressed',String(showFog));wake()};$('motion').onclick=()=>{running=!running;$('motion').setAttribute('aria-pressed',String(running));$('motion').textContent=running?'Pause effects':'Play effects';wake()};$('brief-toggle').onclick=()=>{$('brief-notes').hidden=!$('brief-notes').hidden;$('brief-toggle').textContent=$('brief-notes').hidden?'Show notes':'Hide notes';$('brief-toggle').setAttribute('aria-expanded',String(!$('brief-notes').hidden))};
canvas.addEventListener('wheel',e=>{e.preventDefault();camera=null;const r=canvas.getBoundingClientRect(),x=e.clientX-r.left,y=e.clientY-r.top,old=zoom;zoom=clamp(zoom*Math.exp(-e.deltaY*.0013),.12,6);offset.x=x-(x-offset.x)*zoom/old;offset.y=y-(y-offset.y)*zoom/old;wake()},{passive:false});canvas.addEventListener('pointerdown',e=>{if(e.button!==0)return;camera=null;canvas.setPointerCapture(e.pointerId);drag={id:e.pointerId,x:e.clientX,y:e.clientY}});canvas.addEventListener('pointermove',e=>{if(!drag||drag.id!==e.pointerId)return;offset.x+=e.clientX-drag.x;offset.y+=e.clientY-drag.y;drag.x=e.clientX;drag.y=e.clientY;wake()});const end=()=>drag=null;canvas.addEventListener('pointerup',end);canvas.addEventListener('pointercancel',end);window.addEventListener('blur',end);window.addEventListener('keydown',e=>{if(e.target.matches('button,a,input,select'))return;if(['1','2','3'].includes(e.key))go(['country','region','battle'][Number(e.key)-1])});
let requested=false;function schedule(){if(!requested){requested=true;requestAnimationFrame(frame)}}function wake(){dirty=true;schedule()}
function frame(now){requested=false;if(document.hidden){last=now;return}const dt=last?Math.min((now-last)/1000,.06):0;if(now-last<33&&!dirty&&!camera){if(running)schedule();return;}last=now;if(running){t+=dt;if(t<pushUntil){front=Math.min(250,front+dt*28);if(front>20&&showCover&&$('cover-text').textContent!=='Infantry advancing / cover lost')$('cover-text').textContent='Infantry advancing / cover lost'}if(t-lastAuto>4){lastAuto=t;addEffect(hub.x+560+rand()*200,hub.y+80+rand()*240,true)}for(let i=shells.length-1;i>=0;i--){const s=shells[i];if(t>=s.start+s.duration){addEffect(s.tx,s.ty);shells.splice(i,1)}}for(let i=effects.length-1;i>=0;i--)if(t-effects[i].born>2.7)effects.splice(i,1)}if(camera){const k=clamp((now-camera.start)/280,0,1),e=1-(1-k)**3;zoom=camera.from.zoom+(camera.to.zoom-camera.from.zoom)*e;offset.x=camera.from.x+(camera.to.x-camera.from.x)*e;offset.y=camera.from.y+(camera.to.y-camera.from.y)*e;if(k===1)camera=null;wake()}if(running||dirty){draw();dirty=false}if(running||camera)schedule()}
reduce.addEventListener('change',()=>{if(reduce.matches){running=false;camera=null;$('motion').textContent='Play effects';$('motion').setAttribute('aria-pressed','false');wake()}});
makeBase();new ResizeObserver(resize).observe(canvas);resize();$('motion').setAttribute('aria-pressed',String(running));$('motion').textContent=running?'Pause effects':'Play effects';document.addEventListener('visibilitychange',()=>{last=0;if(!document.hidden)wake()});wake();
})();
