'use strict';
const fs=require('node:fs'),path=require('node:path');
const root=path.resolve(__dirname,'..'),out=path.join(root,'dist');
const files=['index.html','styles.css','game.js','multiplayer-client.js','fog.js','projection.js','ground-detail.js','simulation.js','geography.js','terrain-art.js','terrain.js','world.js','territory.js','save-validation.js','campaign.js','models.js','preview/model-yard.html','preview/model-yard.css','preview/model-yard.js','preview/visual-lab.html','preview/visual-lab.css','preview/visual-lab.js','docs/model-art-pass.md','docs/visual-research.md','docs/seeded-terrain.md','docs/security-reliability-audit.md','docs/online-play.md'];
function serverURL(value){if(!value)return null;const url=new URL(value);if(url.protocol!=='wss:')throw Error('Public multiplayer endpoint must use wss://.');if(url.username||url.password||url.hash||url.search)throw Error('Use a plain server URL without credentials or query parameters.');return url;}
function build(endpoint=process.env.MULTIPLAYER_SERVER_URL){
 const server=serverURL(endpoint);
 // Only clear our own generated output, never a user directory or symlink.
 if(fs.existsSync(out)){if(fs.lstatSync(out).isSymbolicLink()||!fs.existsSync(path.join(out,'.living-frontiers-build')))throw Error('dist is not a recognised generated directory.');if(path.resolve(out)!==path.join(root,'dist'))throw Error('Unsafe build directory.');fs.rmSync(out,{recursive:true});}
 fs.mkdirSync(out,{recursive:true});fs.writeFileSync(path.join(out,'.living-frontiers-build'),'Generated by scripts/build-static.cjs\n');
 for(const file of files){const source=path.join(root,file);if(!fs.existsSync(source))throw Error('Missing public asset: '+file);const target=path.join(out,file);fs.mkdirSync(path.dirname(target),{recursive:true});fs.copyFileSync(source,target);}
 let html=fs.readFileSync(path.join(out,'index.html'),'utf8');
 if(server)html=html.replace('</head>',`  <meta name="multiplayer-server" content="${server.href.replaceAll('&','&amp;').replaceAll('"','&quot;')}">\n</head>`);
 const connect=server?`'self' ${server.origin}`:"'none'";
 const policy=`default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; connect-src ${connect}; object-src 'none'; base-uri 'none'; form-action 'none'`;
 // Pages does not offer arbitrary response headers; retain the supported CSP subset in HTML.
 html=html.replace('<meta charset="utf-8">',`<meta charset="utf-8">\n  <meta http-equiv="Content-Security-Policy" content="${policy}">\n  <meta name="referrer" content="no-referrer">`);
 fs.writeFileSync(path.join(out,'index.html'),html);
 fs.writeFileSync(path.join(out,'_headers'),`/*\n  Content-Security-Policy: ${policy}; frame-ancestors 'none'\n  X-Content-Type-Options: nosniff\n  Referrer-Policy: no-referrer\n  X-Frame-Options: DENY\n  Cache-Control: no-cache\n`);
 fs.writeFileSync(path.join(out,'.nojekyll'),'');
 console.log(`Public build: ${out}. ${server?'Multiplayer endpoint configured.':'Solo demo; multiplayer server not connected.'}`);
 return out;
}
if(require.main===module)build();
module.exports={build,files,serverURL};
